export const IMAGE_BASE_URL = 'https://pub-42a385b873274532b0f776d49ed5efc4.r2.dev'

export const IMAGES = {
    // General Images
    background: `${IMAGE_BASE_URL}/image/background.jpg`,
    hero1: `${IMAGE_BASE_URL}/image/hero1.jpg`,
    hero2: `${IMAGE_BASE_URL}/image/hero2.jpg`,
    hero3: `${IMAGE_BASE_URL}/image/hero3.jpg`,
    intro1: `${IMAGE_BASE_URL}/image/intro1.jpg`,
    intro2: `${IMAGE_BASE_URL}/image/intro2.jpg`,
    intro3: `${IMAGE_BASE_URL}/image/intro3.jpg`,
    logo_rmbg: `${IMAGE_BASE_URL}/image/logo-rmbg.png`,
    logo: `${IMAGE_BASE_URL}/image/logo.png`,
    service: `${IMAGE_BASE_URL}/image/service.jpg`,

    // Portfolio thumbnails
    nathanxtracy: `${IMAGE_BASE_URL}/image/nathanxtracy.webp`,
    tienxwilliam: `${IMAGE_BASE_URL}/image/tienxwilliam.webp`,
    duyenxsteven: `${IMAGE_BASE_URL}/image/duyenxsteven.webp`,
    vanxtuc: `${IMAGE_BASE_URL}/image/vanxtuc.webp`,
    tranxtai: `${IMAGE_BASE_URL}/image/tranxtai.webp`,
    mayxmat: `${IMAGE_BASE_URL}/image/mayxmat.webp`,
    vietxquynh: `${IMAGE_BASE_URL}/image/vietxquynh.webp`,
    nganxnhat: `${IMAGE_BASE_URL}/image/nganxnhat.webp`,
    duyxmy: `${IMAGE_BASE_URL}/image/duyxmy.webp`,
    eventxbenang: `${IMAGE_BASE_URL}/image/eventxbenang.webp`,
    phuongxhien: `${IMAGE_BASE_URL}/image/phuongxhien.webp`,
    phuongxhien2: `${IMAGE_BASE_URL}/image/phuongxhien2.webp`,
    elopement: `${IMAGE_BASE_URL}/image/elopement.webp`,
    hieuxbrian: `${IMAGE_BASE_URL}/image/hieuxbrian.webp`,
    hanxtuan: `${IMAGE_BASE_URL}/image/hanxtuan.webp`,

    // Nathan x Tracy gallery
    nathanxtracy1: `${IMAGE_BASE_URL}/image/nathanxtracy1.webp?t=${Date.now()}`,
    nathanxtracy2: `${IMAGE_BASE_URL}/image/nathanxtracy2.webp?t=${Date.now()}`,
    nathanxtracy3: `${IMAGE_BASE_URL}/image/nathanxtracy3.webp?t=${Date.now()}`,
    nathanxtracy4: `${IMAGE_BASE_URL}/image/nathanxtracy4.webp?t=${Date.now()}`,
    nathanxtracy5: `${IMAGE_BASE_URL}/image/nathanxtracy5.webp?t=${Date.now()}`,
    nathanxtracy6: `${IMAGE_BASE_URL}/image/nathanxtracy6.webp?t=${Date.now()}`,
    nathanxtracy7: `${IMAGE_BASE_URL}/image/nathanxtracy7.webp?t=${Date.now()}`,
    nathanxtracy8: `${IMAGE_BASE_URL}/image/nathanxtracy8.webp?t=${Date.now()}`,
    nathanxtracy9: `${IMAGE_BASE_URL}/image/nathanxtracy9.webp?t=${Date.now()}`,
    nathanxtracy10: `${IMAGE_BASE_URL}/image/nathanxtracy10.webp?t=${Date.now()}`,
    nathanxtracy11: `${IMAGE_BASE_URL}/image/nathanxtracy11.webp?t=${Date.now()}`,
    nathanxtracy12: `${IMAGE_BASE_URL}/image/nathanxtracy12.webp?t=${Date.now()}`,
    nathanxtracy13: `${IMAGE_BASE_URL}/image/nathanxtracy13.webp?t=${Date.now()}`,

    // Tien x William gallery
    tienxwillam1: `${IMAGE_BASE_URL}/image/tienxwillam1.webp?t=${Date.now()}`,
    tienxwillam2: `${IMAGE_BASE_URL}/image/tienxwillam2.webp?t=${Date.now()}`,
    tienxwillam3: `${IMAGE_BASE_URL}/image/tienxwillam3.webp?t=${Date.now()}`,
    tienxwillam4: `${IMAGE_BASE_URL}/image/tienxwillam4.webp?t=${Date.now()}`,
    tienxwillam5: `${IMAGE_BASE_URL}/image/tienxwillam5.webp?t=${Date.now()}`,
    tienxwillam6: `${IMAGE_BASE_URL}/image/tienxwillam6.webp?t=${Date.now()}`,
    tienxwillam7: `${IMAGE_BASE_URL}/image/tienxwillam7.webp?t=${Date.now()}`,
    tienxwillam8: `${IMAGE_BASE_URL}/image/tienxwillam8.webp?t=${Date.now()}`,
    tienxwillam9: `${IMAGE_BASE_URL}/image/tienxwillam9.webp?t=${Date.now()}`,
    tienxwillam10: `${IMAGE_BASE_URL}/image/tienxwillam10.webp?t=${Date.now()}`,

    // Han x Tuan gallery
    hanxtuan1: `${IMAGE_BASE_URL}/image/hanxtuan1.webp?t=${Date.now()}`,
    hanxtuan2: `${IMAGE_BASE_URL}/image/hanxtuan2.webp?t=${Date.now()}`,
    hanxtuan3: `${IMAGE_BASE_URL}/image/hanxtuan3.webp?t=${Date.now()}`,
    hanxtuan4: `${IMAGE_BASE_URL}/image/hanxtuan4.webp?t=${Date.now()}`,
    hanxtuan5: `${IMAGE_BASE_URL}/image/hanxtuan5.webp?t=${Date.now()}`,
    hanxtuan6: `${IMAGE_BASE_URL}/image/hanxtuan6.webp?t=${Date.now()}`,
    hanxtuan7: `${IMAGE_BASE_URL}/image/hanxtuan7.webp?t=${Date.now()}`,
    hanxtuan8: `${IMAGE_BASE_URL}/image/hanxtuan8.webp?t=${Date.now()}`,
    hanxtuan9: `${IMAGE_BASE_URL}/image/hanxtuan9.webp?t=${Date.now()}`,
    hanxtuan10: `${IMAGE_BASE_URL}/image/hanxtuan10.webp?t=${Date.now()}`,
    hanxtuan11: `${IMAGE_BASE_URL}/image/hanxtuan11.webp?t=${Date.now()}`,
    hanxtuan12: `${IMAGE_BASE_URL}/image/hanxtuan12.webp?t=${Date.now()}`,

    // Duyen x Steven gallery
    duyenxsteven1: `${IMAGE_BASE_URL}/image/duyenxsteven1.webp?t=${Date.now()}`,
    duyenxsteven2: `${IMAGE_BASE_URL}/image/duyenxsteven2.webp?t=${Date.now()}`,
    duyenxsteven3: `${IMAGE_BASE_URL}/image/duyenxsteven3.webp?t=${Date.now()}`,
    duyenxsteven4: `${IMAGE_BASE_URL}/image/duyenxsteven4.webp?t=${Date.now()}`,
    duyenxsteven5: `${IMAGE_BASE_URL}/image/duyenxsteven5.webp?t=${Date.now()}`,
    duyenxsteven6: `${IMAGE_BASE_URL}/image/duyenxsteven6.webp?t=${Date.now()}`,
    duyenxsteven7: `${IMAGE_BASE_URL}/image/duyenxsteven7.webp?t=${Date.now()}`,
    duyenxsteven8: `${IMAGE_BASE_URL}/image/duyenxsteven8.webp?t=${Date.now()}`,
    duyenxsteven9: `${IMAGE_BASE_URL}/image/duyenxsteven9.webp?t=${Date.now()}`,
    duyenxsteven10: `${IMAGE_BASE_URL}/image/duyenxsteven10.webp?t=${Date.now()}`,
    duyenxsteven11: `${IMAGE_BASE_URL}/image/duyenxsteven11.webp?t=${Date.now()}`,
    duyenxsteven12: `${IMAGE_BASE_URL}/image/duyenxsteven12.webp?t=${Date.now()}`,
    duyenxsteven13: `${IMAGE_BASE_URL}/image/duyenxsteven13.webp?t=${Date.now()}`,
    duyenxsteven14: `${IMAGE_BASE_URL}/image/duyenxsteven14.webp?t=${Date.now()}`,
    duyenxsteven15: `${IMAGE_BASE_URL}/image/duyenxsteven15.webp?t=${Date.now()}`,
    duyenxsteven16: `${IMAGE_BASE_URL}/image/duyenxsteven16.webp?t=${Date.now()}`,
    duyenxsteven17: `${IMAGE_BASE_URL}/image/duyenxsteven17.webp?t=${Date.now()}`,
    duyenxsteven18: `${IMAGE_BASE_URL}/image/duyenxsteven18.webp?t=${Date.now()}`,
    duyenxsteven19: `${IMAGE_BASE_URL}/image/duyenxsteven19.webp?t=${Date.now()}`,

    // Van x Tuc gallery
    vanxtuc1: `${IMAGE_BASE_URL}/image/vanxtuc1.webp?t=${Date.now()}`,
    vanxtuc2: `${IMAGE_BASE_URL}/image/vanxtuc2.webp?t=${Date.now()}`,
    vanxtuc3: `${IMAGE_BASE_URL}/image/vanxtuc3.webp?t=${Date.now()}`,
    vanxtuc4: `${IMAGE_BASE_URL}/image/vanxtuc4.webp?t=${Date.now()}`,
    vanxtuc5: `${IMAGE_BASE_URL}/image/vanxtuc5.webp?t=${Date.now()}`,
    vanxtuc6: `${IMAGE_BASE_URL}/image/vanxtuc6.webp?t=${Date.now()}`,
    vanxtuc7: `${IMAGE_BASE_URL}/image/vanxtuc7.webp?t=${Date.now()}`,
    vanxtuc8: `${IMAGE_BASE_URL}/image/vanxtuc8.webp?t=${Date.now()}`,
    vanxtuc9: `${IMAGE_BASE_URL}/image/vanxtuc9.webp?t=${Date.now()}`,
    vanxtuc10: `${IMAGE_BASE_URL}/image/vanxtuc10.webp?t=${Date.now()}`,
    vanxtuc11: `${IMAGE_BASE_URL}/image/vanxtuc11.webp?t=${Date.now()}`,
    vanxtuc12: `${IMAGE_BASE_URL}/image/vanxtuc12.webp?t=${Date.now()}`,
    vanxtuc13: `${IMAGE_BASE_URL}/image/vanxtuc13.webp?t=${Date.now()}`,
    vanxtuc14: `${IMAGE_BASE_URL}/image/vanxtuc14.webp?t=${Date.now()}`,

    // Tran x Tai gallery
    tranxtai1: `${IMAGE_BASE_URL}/image/tranxtai1.webp?t=${Date.now()}`,
    tranxtai2: `${IMAGE_BASE_URL}/image/tranxtai2.webp?t=${Date.now()}`,
    tranxtai3: `${IMAGE_BASE_URL}/image/tranxtai3.webp?t=${Date.now()}`,
    tranxtai4: `${IMAGE_BASE_URL}/image/tranxtai4.webp?t=${Date.now()}`,
    tranxtai5: `${IMAGE_BASE_URL}/image/tranxtai5.webp?t=${Date.now()}`,
    tranxtai6: `${IMAGE_BASE_URL}/image/tranxtai6.webp?t=${Date.now()}`,
    tranxtai7: `${IMAGE_BASE_URL}/image/tranxtai7.webp?t=${Date.now()}`,
    tranxtai8: `${IMAGE_BASE_URL}/image/tranxtai8.webp?t=${Date.now()}`,
    tranxtai9: `${IMAGE_BASE_URL}/image/tranxtai9.webp?t=${Date.now()}`,
    tranxtai10: `${IMAGE_BASE_URL}/image/tranxtai10.webp?t=${Date.now()}`,
    tranxtai11: `${IMAGE_BASE_URL}/image/tranxtai11.webp?t=${Date.now()}`,
    tranxtai12: `${IMAGE_BASE_URL}/image/tranxtai12.webp?t=${Date.now()}`,

    // May x Mat gallery
    mayxmat1: `${IMAGE_BASE_URL}/image/mayxmat1.webp?t=${Date.now()}`,
    mayxmat2: `${IMAGE_BASE_URL}/image/mayxmat2.webp?t=${Date.now()}`,
    mayxmat3: `${IMAGE_BASE_URL}/image/mayxmat3.webp?t=${Date.now()}`,
    mayxmat4: `${IMAGE_BASE_URL}/image/mayxmat4.webp?t=${Date.now()}`,
    mayxmat5: `${IMAGE_BASE_URL}/image/mayxmat5.webp?t=${Date.now()}`,
    mayxmat6: `${IMAGE_BASE_URL}/image/mayxmat6.webp?t=${Date.now()}`,
    mayxmat7: `${IMAGE_BASE_URL}/image/mayxmat7.webp?t=${Date.now()}`,
    mayxmat8: `${IMAGE_BASE_URL}/image/mayxmat8.webp?t=${Date.now()}`,
    mayxmat9: `${IMAGE_BASE_URL}/image/mayxmat9.webp?t=${Date.now()}`,
    mayxmat10: `${IMAGE_BASE_URL}/image/mayxmat10.webp?t=${Date.now()}`,
    mayxmat11: `${IMAGE_BASE_URL}/image/mayxmat11.webp?t=${Date.now()}`,
    mayxmat12: `${IMAGE_BASE_URL}/image/mayxmat12.webp?t=${Date.now()}`,
    mayxmat13: `${IMAGE_BASE_URL}/image/mayxmat13.webp?t=${Date.now()}`,
    mayxmat14: `${IMAGE_BASE_URL}/image/mayxmat14.webp?t=${Date.now()}`,
    mayxmat15: `${IMAGE_BASE_URL}/image/mayxmat15.webp?t=${Date.now()}`,
    mayxmat16: `${IMAGE_BASE_URL}/image/mayxmat16.webp?t=${Date.now()}`,
    mayxmat17: `${IMAGE_BASE_URL}/image/mayxmat17.webp?t=${Date.now()}`,
    mayxmat18: `${IMAGE_BASE_URL}/image/mayxmat18.webp?t=${Date.now()}`,
    mayxmat19: `${IMAGE_BASE_URL}/image/mayxmat19.webp?t=${Date.now()}`,
    mayxmat20: `${IMAGE_BASE_URL}/image/mayxmat20.webp?t=${Date.now()}`,

    // Hieu x Brian gallery
    hieuxbrian1: `${IMAGE_BASE_URL}/image/hieuxbrian1.webp?t=${Date.now()}`,
    hieuxbrian2: `${IMAGE_BASE_URL}/image/hieuxbrian2.webp?t=${Date.now()}`,
    hieuxbrian3: `${IMAGE_BASE_URL}/image/hieuxbrian3.webp?t=${Date.now()}`,
    hieuxbrian4: `${IMAGE_BASE_URL}/image/hieuxbrian4.webp?t=${Date.now()}`,
    hieuxbrian5: `${IMAGE_BASE_URL}/image/hieuxbrian5.webp?t=${Date.now()}`,
    hieuxbrian6: `${IMAGE_BASE_URL}/image/hieuxbrian6.webp?t=${Date.now()}`,
    hieuxbrian7: `${IMAGE_BASE_URL}/image/hieuxbrian7.webp?t=${Date.now()}`,
    hieuxbrian8: `${IMAGE_BASE_URL}/image/hieuxbrian8.webp?t=${Date.now()}`,
    hieuxbrian9: `${IMAGE_BASE_URL}/image/hieuxbrian9.webp?t=${Date.now()}`,
    hieuxbrian10: `${IMAGE_BASE_URL}/image/hieuxbrian10.webp?t=${Date.now()}`,
    hieuxbrian11: `${IMAGE_BASE_URL}/image/hieuxbrian11.webp?t=${Date.now()}`,
    hieuxbrian12: `${IMAGE_BASE_URL}/image/hieuxbrian12.webp?t=${Date.now()}`,
    hieuxbrian13: `${IMAGE_BASE_URL}/image/hieuxbrian13.webp?t=${Date.now()}`,
    hieuxbrian14: `${IMAGE_BASE_URL}/image/hieuxbrian14.webp?t=${Date.now()}`,
    hieuxbrian15: `${IMAGE_BASE_URL}/image/hieuxbrian15.webp?t=${Date.now()}`,
    hieuxbrian16: `${IMAGE_BASE_URL}/image/hieuxbrian16.webp?t=${Date.now()}`,

    // Duy x My gallery
    duyxmy1: `${IMAGE_BASE_URL}/image/duyxmy1.webp?t=${Date.now()}`,
    duyxmy2: `${IMAGE_BASE_URL}/image/duyxmy2.webp?t=${Date.now()}`,
    duyxmy3: `${IMAGE_BASE_URL}/image/duyxmy3.webp?t=${Date.now()}`,
    duyxmy4: `${IMAGE_BASE_URL}/image/duyxmy4.webp?t=${Date.now()}`,
    duyxmy5: `${IMAGE_BASE_URL}/image/duyxmy5.webp?t=${Date.now()}`,
    duyxmy6: `${IMAGE_BASE_URL}/image/duyxmy6.webp?t=${Date.now()}`,
    duyxmy7: `${IMAGE_BASE_URL}/image/duyxmy7.webp?t=${Date.now()}`,
    duyxmy8: `${IMAGE_BASE_URL}/image/duyxmy8.webp?t=${Date.now()}`,
    duyxmy9: `${IMAGE_BASE_URL}/image/duyxmy9.webp?t=${Date.now()}`,
    duyxmy10: `${IMAGE_BASE_URL}/image/duyxmy10.webp?t=${Date.now()}`,
    duyxmy11: `${IMAGE_BASE_URL}/image/duyxmy11.webp?t=${Date.now()}`,
    duyxmy12: `${IMAGE_BASE_URL}/image/duyxmy12.webp?t=${Date.now()}`,
    duyxmy13: `${IMAGE_BASE_URL}/image/duyxmy13.webp?t=${Date.now()}`,
    duyxmy14: `${IMAGE_BASE_URL}/image/duyxmy14.webp?t=${Date.now()}`,
    duyxmy15: `${IMAGE_BASE_URL}/image/duyxmy15.webp?t=${Date.now()}`,
    duyxmy16: `${IMAGE_BASE_URL}/image/duyxmy16.webp?t=${Date.now()}`,
    duyxmy17: `${IMAGE_BASE_URL}/image/duyxmy17.webp?t=${Date.now()}`,
    duyxmy18: `${IMAGE_BASE_URL}/image/duyxmy18.webp?t=${Date.now()}`,
    duyxmy19: `${IMAGE_BASE_URL}/image/duyxmy19.webp?t=${Date.now()}`,
    duyxmy20: `${IMAGE_BASE_URL}/image/duyxmy20.webp?t=${Date.now()}`,

    // Phuong x Hien gallery
    phuongxhien1: `${IMAGE_BASE_URL}/image/phuongxhien1.webp?t=${Date.now()}`,
    phuongxhien2: `${IMAGE_BASE_URL}/image/phuongxhien2.webp?t=${Date.now()}`,
    phuongxhien3: `${IMAGE_BASE_URL}/image/phuongxhien3.webp?t=${Date.now()}`,
    phuongxhien4: `${IMAGE_BASE_URL}/image/phuongxhien4.webp?t=${Date.now()}`,
    phuongxhien5: `${IMAGE_BASE_URL}/image/phuongxhien5.webp?t=${Date.now()}`,
    phuongxhien6: `${IMAGE_BASE_URL}/image/phuongxhien6.webp?t=${Date.now()}`,
    phuongxhien7: `${IMAGE_BASE_URL}/image/phuongxhien7.webp?t=${Date.now()}`,
    phuongxhien8: `${IMAGE_BASE_URL}/image/phuongxhien8.webp?t=${Date.now()}`,
    phuongxhien9: `${IMAGE_BASE_URL}/image/phuongxhien9.webp?t=${Date.now()}`,
    phuongxhien10: `${IMAGE_BASE_URL}/image/phuongxhien10.webp?t=${Date.now()}`,
    phuongxhien11: `${IMAGE_BASE_URL}/image/phuongxhien11.webp?t=${Date.now()}`,
    phuongxhien12: `${IMAGE_BASE_URL}/image/phuongxhien12.webp?t=${Date.now()}`,
    phuongxhien13: `${IMAGE_BASE_URL}/image/phuongxhien13.webp?t=${Date.now()}`,
    phuongxhien14: `${IMAGE_BASE_URL}/image/phuongxhien14.webp?t=${Date.now()}`,
    phuongxhien17: `${IMAGE_BASE_URL}/image/phuongxhien17.webp?t=${Date.now()}`,
    phuongxhien18: `${IMAGE_BASE_URL}/image/phuongxhien18.webp?t=${Date.now()}`,
    phuongxhien19: `${IMAGE_BASE_URL}/image/phuongxhien19.webp?t=${Date.now()}`,
    phuongxhien20: `${IMAGE_BASE_URL}/image/phuongxhien20.webp?t=${Date.now()}`,
    phuongxhien21: `${IMAGE_BASE_URL}/image/phuongxhien21.webp?t=${Date.now()}`,

    // Phuong x Hien 2 gallery
    phuongxhien2_1: `${IMAGE_BASE_URL}/image/phuongxhien2.1.webp?t=${Date.now()}`,
    phuongxhien2_2: `${IMAGE_BASE_URL}/image/phuongxhien2.2.webp?t=${Date.now()}`,
    phuongxhien2_3: `${IMAGE_BASE_URL}/image/phuongxhien2.3.webp?t=${Date.now()}`,
    phuongxhien2_4: `${IMAGE_BASE_URL}/image/phuongxhien2.4.webp?t=${Date.now()}`,
    phuongxhien2_5: `${IMAGE_BASE_URL}/image/phuongxhien2.5.webp?t=${Date.now()}`,
    phuongxhien2_6: `${IMAGE_BASE_URL}/image/phuongxhien2.6.webp?t=${Date.now()}`,
    phuongxhien2_7: `${IMAGE_BASE_URL}/image/phuongxhien2.7.webp?t=${Date.now()}`,
    phuongxhien2_8: `${IMAGE_BASE_URL}/image/phuongxhien2.8.webp?t=${Date.now()}`,
    phuongxhien2_9: `${IMAGE_BASE_URL}/image/phuongxhien2.9.webp?t=${Date.now()}`,
    phuongxhien2_10: `${IMAGE_BASE_URL}/image/phuongxhien2.10.webp?t=${Date.now()}`,
    phuongxhien2_11: `${IMAGE_BASE_URL}/image/phuongxhien2.11.webp?t=${Date.now()}`,
    phuongxhien2_12: `${IMAGE_BASE_URL}/image/phuongxhien2.12.webp?t=${Date.now()}`,
    phuongxhien2_13: `${IMAGE_BASE_URL}/image/phuongxhien2.13.webp?t=${Date.now()}`,
    phuongxhien2_14: `${IMAGE_BASE_URL}/image/phuongxhien2.14.webp?t=${Date.now()}`,

    // Elopment gallery
    elopement1: `${IMAGE_BASE_URL}/image/elopement1.webp?t=${Date.now()}`,
    elopement2: `${IMAGE_BASE_URL}/image/elopement2.webp?t=${Date.now()}`,
    elopement3: `${IMAGE_BASE_URL}/image/elopement3.webp?t=${Date.now()}`,
    elopement4: `${IMAGE_BASE_URL}/image/elopement4.webp?t=${Date.now()}`,
    elopement5: `${IMAGE_BASE_URL}/image/elopement5.webp?t=${Date.now()}`,
    elopement6: `${IMAGE_BASE_URL}/image/elopement6.webp?t=${Date.now()}`,
    elopement7: `${IMAGE_BASE_URL}/image/elopement7.webp?t=${Date.now()}`,
    elopement8: `${IMAGE_BASE_URL}/image/elopement8.webp?t=${Date.now()}`,
    elopement9: `${IMAGE_BASE_URL}/image/elopement9.webp?t=${Date.now()}`,
    elopement10: `${IMAGE_BASE_URL}/image/elopement10.webp?t=${Date.now()}`,
    elopement11: `${IMAGE_BASE_URL}/image/elopement11.webp?t=${Date.now()}`,
    elopement12: `${IMAGE_BASE_URL}/image/elopement12.webp?t=${Date.now()}`,
    elopement13: `${IMAGE_BASE_URL}/image/elopement13.webp?t=${Date.now()}`,
    elopement14: `${IMAGE_BASE_URL}/image/elopement14.webp?t=${Date.now()}`,
    elopement15: `${IMAGE_BASE_URL}/image/elopement15.webp?t=${Date.now()}`,
    elopement16: `${IMAGE_BASE_URL}/image/elopement16.webp?t=${Date.now()}`,

     // Ant Team gallery
    antweddingteam1: `${IMAGE_BASE_URL}/image/antweddingteam1.webp?t=${Date.now()}`,
    antweddingteam2: `${IMAGE_BASE_URL}/image/antweddingteam2.webp?t=${Date.now()}`,
    antweddingteam3: `${IMAGE_BASE_URL}/image/antweddingteam3.webp?t=${Date.now()}`,
    antweddingteam4: `${IMAGE_BASE_URL}/image/antweddingteam4.webp?t=${Date.now()}`,
    antweddingteam5: `${IMAGE_BASE_URL}/image/antweddingteam5.webp?t=${Date.now()}`,
    antweddingteam6: `${IMAGE_BASE_URL}/image/antweddingteam6.webp?t=${Date.now()}`,
    antweddingteam7: `${IMAGE_BASE_URL}/image/antweddingteam7.webp?t=${Date.now()}`,
    antweddingteam8: `${IMAGE_BASE_URL}/image/antweddingteam8.webp?t=${Date.now()}`,
    antweddingteam9: `${IMAGE_BASE_URL}/image/antweddingteam9.webp?t=${Date.now()}`,
    antweddingteam10: `${IMAGE_BASE_URL}/image/antweddingteam10.webp?t=${Date.now()}`,
    antweddingteam11: `${IMAGE_BASE_URL}/image/antweddingteam11.webp?t=${Date.now()}`,
    antweddingteam12: `${IMAGE_BASE_URL}/image/antweddingteam12.webp?t=${Date.now()}`,
    antweddingteam13: `${IMAGE_BASE_URL}/image/antweddingteam13.webp?t=${Date.now()}`,
    antweddingteam14: `${IMAGE_BASE_URL}/image/antweddingteam14.webp?t=${Date.now()}`,
    antweddingteam15: `${IMAGE_BASE_URL}/image/antweddingteam15.webp?t=${Date.now()}`,
    antweddingteam16: `${IMAGE_BASE_URL}/image/antweddingteam16.webp?t=${Date.now()}`,
    antweddingteam17: `${IMAGE_BASE_URL}/image/antweddingteam17.webp?t=${Date.now()}`,
    antweddingteam18: `${IMAGE_BASE_URL}/image/antweddingteam18.webp?t=${Date.now()}`,
    antweddingteam19: `${IMAGE_BASE_URL}/image/antweddingteam19.webp?t=${Date.now()}`,
    antweddingteam20: `${IMAGE_BASE_URL}/image/antweddingteam20.webp?t=${Date.now()}`,
    antweddingteam21: `${IMAGE_BASE_URL}/image/antweddingteam21.webp?t=${Date.now()}`,
    antweddingteam22: `${IMAGE_BASE_URL}/image/antweddingteam22.webp?t=${Date.now()}`,
    antweddingteam23: `${IMAGE_BASE_URL}/image/antweddingteam23.webp?t=${Date.now()}`,
    antweddingteam24: `${IMAGE_BASE_URL}/image/antweddingteam24.webp?t=${Date.now()}`,
    antweddingteam25: `${IMAGE_BASE_URL}/image/antweddingteam25.webp?t=${Date.now()}`,
}
