export const IMAGE_BASE_URL = 'https://pub-42a385b873274532b0f776d49ed5efc4.r2.dev'

export const IMAGES = {
    background: `${IMAGE_BASE_URL}/image/background.jpg`,
    hero1: `${IMAGE_BASE_URL}/image/hero1.jpg`,
    hero2: `${IMAGE_BASE_URL}/image/hero2.jpg`,
    hero3: `${IMAGE_BASE_URL}/image/hero3.jpg`,
    intro1: `${IMAGE_BASE_URL}/image/intro1.jpg`,
    intro2: `${IMAGE_BASE_URL}/image/intro2.jpg`,
    intro3: `${IMAGE_BASE_URL}/image/intro3.jpg`,
    logo_rmbg: `${IMAGE_BASE_URL}/image/logo-rmbg.png`,
    logo: `${IMAGE_BASE_URL}/image/logo.png`,
    service: `${IMAGE_BASE_URL}/image/service.jpg`,
    nathanxtracy: `${IMAGE_BASE_URL}/image/nathanxtracy.webp`,
    tienxwilliam: `${IMAGE_BASE_URL}/image/tienxwilliam.webp`,
    duyenxsteven: `${IMAGE_BASE_URL}/image/duyenxsteven.webp`,
    vanxtuc: `${IMAGE_BASE_URL}/image/vanxtuc.webp`,
    tranxtai: `${IMAGE_BASE_URL}/image/tranxtai.webp`,
    mayxmat: `${IMAGE_BASE_URL}/image/mayxmat.webp`,
    vietxquynh: `${IMAGE_BASE_URL}/image/vietxquynh.webp`,
    nganxnhat: `${IMAGE_BASE_URL}/image/nganxnhat.webp`,
    duyxmy: `${IMAGE_BASE_URL}/image/duyxmy.webp`,
    eventxbenang: `${IMAGE_BASE_URL}/image/eventxbenang.webp`,
    phuongxhien: `${IMAGE_BASE_URL}/image/phuongxhien.webp`,
    phuongxhien2: `${IMAGE_BASE_URL}/image/phuongxhien2.webp`,
    duyxmy: `${IMAGE_BASE_URL}/image/duyxmy.webp`,
    elopement: `${IMAGE_BASE_URL}/image/elopement.webp`,
    hieuxbrian: `${IMAGE_BASE_URL}/image/hieuxbrian.webp`,
}