export const IMAGE_BASE_URL = 'https://pub-42a385b873274532b0f776d49ed5efc4.r2.dev'

export const IMAGES = {
    // General Images
    background: `${IMAGE_BASE_URL}/image/background.jpg`,
    hero1: `${IMAGE_BASE_URL}/image/hero1.jpg`,
    hero2: `${IMAGE_BASE_URL}/image/hero2.jpg`,
    hero6: `${IMAGE_BASE_URL}/image/hero6.jpg`,
    hero7: `${IMAGE_BASE_URL}/image/hero7.jpg`,
    intro1: `${IMAGE_BASE_URL}/image/intro1.jpg`,
    intro2: `${IMAGE_BASE_URL}/image/intro2.jpg`,
    intro3: `${IMAGE_BASE_URL}/image/intro3.jpg`,
    logo_rmbg: `${IMAGE_BASE_URL}/image/logo-rmbg.png`,
    logo: `${IMAGE_BASE_URL}/image/logo.png`,
    service: `${IMAGE_BASE_URL}/image/service.jpg`,

    // Portfolio thumbnails
    nathanxtracy: `${IMAGE_BASE_URL}/image/nathanxtracy.webp`,
    tienxwilliam: `${IMAGE_BASE_URL}/image/tienxwilliam.webp`,
    duyenxsteven: `${IMAGE_BASE_URL}/image/duyenxsteven.webp`,
    vanxtuc: `${IMAGE_BASE_URL}/image/vanxtuc.webp`,
    tranxtai: `${IMAGE_BASE_URL}/image/tranxtai.webp`,
    mayxmat: `${IMAGE_BASE_URL}/image/mayxmat.webp`,
    vietxquynh: `${IMAGE_BASE_URL}/image/vietxquynh.webp`,
    nganxnhat: `${IMAGE_BASE_URL}/image/nganxnhat.webp`,
    duyxmy: `${IMAGE_BASE_URL}/image/duyxmy.webp`,
    duyxmy2: `${IMAGE_BASE_URL}/image/duyxmy2.webp`,
    trangxvini: `${IMAGE_BASE_URL}/image/trangxvini.webp`,
    eventxbenang: `${IMAGE_BASE_URL}/image/eventxbenang.webp`,
    phuongxhien: `${IMAGE_BASE_URL}/image/phuongxhien.webp`,
    phuongxhien2: `${IMAGE_BASE_URL}/image/phuongxhien2.webp`,
    phuongxhien3: `${IMAGE_BASE_URL}/image/phuongxhien3.webp`,
    elopement: `${IMAGE_BASE_URL}/image/elopement.webp`,
    hieuxbrian: `${IMAGE_BASE_URL}/image/hieuxbrian.webp`,
    hanxtuan: `${IMAGE_BASE_URL}/image/hanxtuan.webp`,
    duyxyen: `${IMAGE_BASE_URL}/image/duyxyen1.webp`,
    thoaxbinh: `${IMAGE_BASE_URL}/image/thoaxbinh1.webp`,
    anxnghi: `${IMAGE_BASE_URL}/image/anxnghi1.webp`,
    anxtoan: `${IMAGE_BASE_URL}/image/anxtoan1.webp`,
    hanxtung: `${IMAGE_BASE_URL}/image/hanxtung1.webp`,
    joshxlinda: `${IMAGE_BASE_URL}/image/joshxlinda1.webp`,
    maimyxtoanem: `${IMAGE_BASE_URL}/image/maimyxtoanem1.webp`,
    nghiaxnguyet: `${IMAGE_BASE_URL}/image/nghiaxnguyet1.webp`,
    thongxhuyen: `${IMAGE_BASE_URL}/image/thongxhuyen1.webp`,
    tramxmax: `${IMAGE_BASE_URL}/image/tramxmax1.webp`,
    tranxtai2: `${IMAGE_BASE_URL}/image/tranxtai2_1.webp`,
    vietxquynh2: `${IMAGE_BASE_URL}/image/vietxquynh2_1.webp`,
    vyxkhang: `${IMAGE_BASE_URL}/image/vyxkhang1.webp`,
    trangxvini: `${IMAGE_BASE_URL}/image/trangxvini1.webp`,

    // Nathan x Tracy gallery
    nathanxtracy1: `${IMAGE_BASE_URL}/image/nathanxtracy1.webp?t=${Date.now()}`,
    nathanxtracy2: `${IMAGE_BASE_URL}/image/nathanxtracy2.webp?t=${Date.now()}`,
    nathanxtracy3: `${IMAGE_BASE_URL}/image/nathanxtracy3.webp?t=${Date.now()}`,
    nathanxtracy4: `${IMAGE_BASE_URL}/image/nathanxtracy4.webp?t=${Date.now()}`,
    nathanxtracy5: `${IMAGE_BASE_URL}/image/nathanxtracy5.webp?t=${Date.now()}`,
    nathanxtracy6: `${IMAGE_BASE_URL}/image/nathanxtracy6.webp?t=${Date.now()}`,
    nathanxtracy7: `${IMAGE_BASE_URL}/image/nathanxtracy7.webp?t=${Date.now()}`,
    nathanxtracy8: `${IMAGE_BASE_URL}/image/nathanxtracy8.webp?t=${Date.now()}`,
    nathanxtracy9: `${IMAGE_BASE_URL}/image/nathanxtracy9.webp?t=${Date.now()}`,
    nathanxtracy10: `${IMAGE_BASE_URL}/image/nathanxtracy10.webp?t=${Date.now()}`,
    nathanxtracy11: `${IMAGE_BASE_URL}/image/nathanxtracy11.webp?t=${Date.now()}`,
    nathanxtracy12: `${IMAGE_BASE_URL}/image/nathanxtracy12.webp?t=${Date.now()}`,
    nathanxtracy13: `${IMAGE_BASE_URL}/image/nathanxtracy13.webp?t=${Date.now()}`,

    // Tien x William gallery
    tienxwillam1: `${IMAGE_BASE_URL}/image/tienxwillam1.webp?t=${Date.now()}`,
    tienxwillam2: `${IMAGE_BASE_URL}/image/tienxwillam2.webp?t=${Date.now()}`,
    tienxwillam3: `${IMAGE_BASE_URL}/image/tienxwillam3.webp?t=${Date.now()}`,
    tienxwillam4: `${IMAGE_BASE_URL}/image/tienxwillam4.webp?t=${Date.now()}`,
    tienxwillam5: `${IMAGE_BASE_URL}/image/tienxwillam5.webp?t=${Date.now()}`,
    tienxwillam6: `${IMAGE_BASE_URL}/image/tienxwillam6.webp?t=${Date.now()}`,
    tienxwillam7: `${IMAGE_BASE_URL}/image/tienxwillam7.webp?t=${Date.now()}`,
    tienxwillam8: `${IMAGE_BASE_URL}/image/tienxwillam8.webp?t=${Date.now()}`,
    tienxwillam9: `${IMAGE_BASE_URL}/image/tienxwillam9.webp?t=${Date.now()}`,
    tienxwillam10: `${IMAGE_BASE_URL}/image/tienxwillam10.webp?t=${Date.now()}`,

    // Han x Tuan gallery
    hanxtuan1: `${IMAGE_BASE_URL}/image/hanxtuan1.webp?t=${Date.now()}`,
    hanxtuan2: `${IMAGE_BASE_URL}/image/hanxtuan2.webp?t=${Date.now()}`,
    hanxtuan3: `${IMAGE_BASE_URL}/image/hanxtuan3.webp?t=${Date.now()}`,
    hanxtuan4: `${IMAGE_BASE_URL}/image/hanxtuan4.webp?t=${Date.now()}`,
    hanxtuan5: `${IMAGE_BASE_URL}/image/hanxtuan5.webp?t=${Date.now()}`,
    hanxtuan6: `${IMAGE_BASE_URL}/image/hanxtuan6.webp?t=${Date.now()}`,
    hanxtuan7: `${IMAGE_BASE_URL}/image/hanxtuan7.webp?t=${Date.now()}`,
    hanxtuan8: `${IMAGE_BASE_URL}/image/hanxtuan8.webp?t=${Date.now()}`,
    hanxtuan9: `${IMAGE_BASE_URL}/image/hanxtuan9.webp?t=${Date.now()}`,
    hanxtuan10: `${IMAGE_BASE_URL}/image/hanxtuan10.webp?t=${Date.now()}`,
    hanxtuan11: `${IMAGE_BASE_URL}/image/hanxtuan11.webp?t=${Date.now()}`,
    hanxtuan12: `${IMAGE_BASE_URL}/image/hanxtuan12.webp?t=${Date.now()}`,

    // Duyen x Steven gallery
    duyenxsteven1: `${IMAGE_BASE_URL}/image/duyenxsteven1.webp?t=${Date.now()}`,
    duyenxsteven2: `${IMAGE_BASE_URL}/image/duyenxsteven2.webp?t=${Date.now()}`,
    duyenxsteven3: `${IMAGE_BASE_URL}/image/duyenxsteven3.webp?t=${Date.now()}`,
    duyenxsteven4: `${IMAGE_BASE_URL}/image/duyenxsteven4.webp?t=${Date.now()}`,
    duyenxsteven5: `${IMAGE_BASE_URL}/image/duyenxsteven5.webp?t=${Date.now()}`,
    duyenxsteven6: `${IMAGE_BASE_URL}/image/duyenxsteven6.webp?t=${Date.now()}`,
    duyenxsteven7: `${IMAGE_BASE_URL}/image/duyenxsteven7.webp?t=${Date.now()}`,
    duyenxsteven8: `${IMAGE_BASE_URL}/image/duyenxsteven8.webp?t=${Date.now()}`,
    duyenxsteven9: `${IMAGE_BASE_URL}/image/duyenxsteven9.webp?t=${Date.now()}`,
    duyenxsteven10: `${IMAGE_BASE_URL}/image/duyenxsteven10.webp?t=${Date.now()}`,
    duyenxsteven11: `${IMAGE_BASE_URL}/image/duyenxsteven11.webp?t=${Date.now()}`,
    duyenxsteven12: `${IMAGE_BASE_URL}/image/duyenxsteven12.webp?t=${Date.now()}`,
    duyenxsteven13: `${IMAGE_BASE_URL}/image/duyenxsteven13.webp?t=${Date.now()}`,
    duyenxsteven14: `${IMAGE_BASE_URL}/image/duyenxsteven14.webp?t=${Date.now()}`,
    duyenxsteven15: `${IMAGE_BASE_URL}/image/duyenxsteven15.webp?t=${Date.now()}`,
    duyenxsteven16: `${IMAGE_BASE_URL}/image/duyenxsteven16.webp?t=${Date.now()}`,
    duyenxsteven17: `${IMAGE_BASE_URL}/image/duyenxsteven17.webp?t=${Date.now()}`,
    duyenxsteven18: `${IMAGE_BASE_URL}/image/duyenxsteven18.webp?t=${Date.now()}`,
    duyenxsteven19: `${IMAGE_BASE_URL}/image/duyenxsteven19.webp?t=${Date.now()}`,

    // Van x Tuc gallery
    vanxtuc1: `${IMAGE_BASE_URL}/image/vanxtuc1.webp?t=${Date.now()}`,
    vanxtuc2: `${IMAGE_BASE_URL}/image/vanxtuc2.webp?t=${Date.now()}`,
    vanxtuc3: `${IMAGE_BASE_URL}/image/vanxtuc3.webp?t=${Date.now()}`,
    vanxtuc4: `${IMAGE_BASE_URL}/image/vanxtuc4.webp?t=${Date.now()}`,
    vanxtuc5: `${IMAGE_BASE_URL}/image/vanxtuc5.webp?t=${Date.now()}`,
    vanxtuc6: `${IMAGE_BASE_URL}/image/vanxtuc6.webp?t=${Date.now()}`,
    vanxtuc7: `${IMAGE_BASE_URL}/image/vanxtuc7.webp?t=${Date.now()}`,
    vanxtuc8: `${IMAGE_BASE_URL}/image/vanxtuc8.webp?t=${Date.now()}`,
    vanxtuc9: `${IMAGE_BASE_URL}/image/vanxtuc9.webp?t=${Date.now()}`,
    vanxtuc10: `${IMAGE_BASE_URL}/image/vanxtuc10.webp?t=${Date.now()}`,
    vanxtuc11: `${IMAGE_BASE_URL}/image/vanxtuc11.webp?t=${Date.now()}`,
    vanxtuc12: `${IMAGE_BASE_URL}/image/vanxtuc12.webp?t=${Date.now()}`,
    vanxtuc13: `${IMAGE_BASE_URL}/image/vanxtuc13.webp?t=${Date.now()}`,
    vanxtuc14: `${IMAGE_BASE_URL}/image/vanxtuc14.webp?t=${Date.now()}`,

    // Tran x Tai gallery
    tranxtai1: `${IMAGE_BASE_URL}/image/tranxtai1.webp?t=${Date.now()}`,
    tranxtai2: `${IMAGE_BASE_URL}/image/tranxtai2.webp?t=${Date.now()}`,
    tranxtai3: `${IMAGE_BASE_URL}/image/tranxtai3.webp?t=${Date.now()}`,
    tranxtai4: `${IMAGE_BASE_URL}/image/tranxtai4.webp?t=${Date.now()}`,
    tranxtai5: `${IMAGE_BASE_URL}/image/tranxtai5.webp?t=${Date.now()}`,
    tranxtai6: `${IMAGE_BASE_URL}/image/tranxtai6.webp?t=${Date.now()}`,
    tranxtai7: `${IMAGE_BASE_URL}/image/tranxtai7.webp?t=${Date.now()}`,
    tranxtai8: `${IMAGE_BASE_URL}/image/tranxtai8.webp?t=${Date.now()}`,
    tranxtai9: `${IMAGE_BASE_URL}/image/tranxtai9.webp?t=${Date.now()}`,
    tranxtai10: `${IMAGE_BASE_URL}/image/tranxtai10.webp?t=${Date.now()}`,
    tranxtai11: `${IMAGE_BASE_URL}/image/tranxtai11.webp?t=${Date.now()}`,
    tranxtai12: `${IMAGE_BASE_URL}/image/tranxtai12.webp?t=${Date.now()}`,

    // May x Mat gallery
    mayxmat1: `${IMAGE_BASE_URL}/image/mayxmat1.webp?t=${Date.now()}`,
    mayxmat2: `${IMAGE_BASE_URL}/image/mayxmat2.webp?t=${Date.now()}`,
    mayxmat3: `${IMAGE_BASE_URL}/image/mayxmat3.webp?t=${Date.now()}`,
    mayxmat4: `${IMAGE_BASE_URL}/image/mayxmat4.webp?t=${Date.now()}`,
    mayxmat5: `${IMAGE_BASE_URL}/image/mayxmat5.webp?t=${Date.now()}`,
    mayxmat6: `${IMAGE_BASE_URL}/image/mayxmat6.webp?t=${Date.now()}`,
    mayxmat7: `${IMAGE_BASE_URL}/image/mayxmat7.webp?t=${Date.now()}`,
    mayxmat8: `${IMAGE_BASE_URL}/image/mayxmat8.webp?t=${Date.now()}`,
    mayxmat9: `${IMAGE_BASE_URL}/image/mayxmat9.webp?t=${Date.now()}`,
    mayxmat10: `${IMAGE_BASE_URL}/image/mayxmat10.webp?t=${Date.now()}`,
    mayxmat11: `${IMAGE_BASE_URL}/image/mayxmat11.webp?t=${Date.now()}`,
    mayxmat12: `${IMAGE_BASE_URL}/image/mayxmat12.webp?t=${Date.now()}`,
    mayxmat13: `${IMAGE_BASE_URL}/image/mayxmat13.webp?t=${Date.now()}`,
    mayxmat14: `${IMAGE_BASE_URL}/image/mayxmat14.webp?t=${Date.now()}`,
    mayxmat15: `${IMAGE_BASE_URL}/image/mayxmat15.webp?t=${Date.now()}`,
    mayxmat16: `${IMAGE_BASE_URL}/image/mayxmat16.webp?t=${Date.now()}`,
    mayxmat17: `${IMAGE_BASE_URL}/image/mayxmat17.webp?t=${Date.now()}`,
    mayxmat18: `${IMAGE_BASE_URL}/image/mayxmat18.webp?t=${Date.now()}`,
    mayxmat19: `${IMAGE_BASE_URL}/image/mayxmat19.webp?t=${Date.now()}`,
    mayxmat20: `${IMAGE_BASE_URL}/image/mayxmat20.webp?t=${Date.now()}`,

    // Hieu x Brian gallery
    hieuxbrian1: `${IMAGE_BASE_URL}/image/hieuxbrian1.webp?t=${Date.now()}`,
    hieuxbrian2: `${IMAGE_BASE_URL}/image/hieuxbrian2.webp?t=${Date.now()}`,
    hieuxbrian3: `${IMAGE_BASE_URL}/image/hieuxbrian3.webp?t=${Date.now()}`,
    hieuxbrian4: `${IMAGE_BASE_URL}/image/hieuxbrian4.webp?t=${Date.now()}`,
    hieuxbrian5: `${IMAGE_BASE_URL}/image/hieuxbrian5.webp?t=${Date.now()}`,
    hieuxbrian6: `${IMAGE_BASE_URL}/image/hieuxbrian6.webp?t=${Date.now()}`,
    hieuxbrian7: `${IMAGE_BASE_URL}/image/hieuxbrian7.webp?t=${Date.now()}`,
    hieuxbrian8: `${IMAGE_BASE_URL}/image/hieuxbrian8.webp?t=${Date.now()}`,
    hieuxbrian9: `${IMAGE_BASE_URL}/image/hieuxbrian9.webp?t=${Date.now()}`,
    hieuxbrian10: `${IMAGE_BASE_URL}/image/hieuxbrian10.webp?t=${Date.now()}`,
    hieuxbrian11: `${IMAGE_BASE_URL}/image/hieuxbrian11.webp?t=${Date.now()}`,
    hieuxbrian12: `${IMAGE_BASE_URL}/image/hieuxbrian12.webp?t=${Date.now()}`,
    hieuxbrian13: `${IMAGE_BASE_URL}/image/hieuxbrian13.webp?t=${Date.now()}`,
    hieuxbrian14: `${IMAGE_BASE_URL}/image/hieuxbrian14.webp?t=${Date.now()}`,
    hieuxbrian15: `${IMAGE_BASE_URL}/image/hieuxbrian15.webp?t=${Date.now()}`,
    hieuxbrian16: `${IMAGE_BASE_URL}/image/hieuxbrian16.webp?t=${Date.now()}`,

    // Duy x My gallery
    duyxmy1: `${IMAGE_BASE_URL}/image/duyxmy1.webp?t=${Date.now()}`,
    duyxmy2: `${IMAGE_BASE_URL}/image/duyxmy2.webp?t=${Date.now()}`,
    duyxmy3: `${IMAGE_BASE_URL}/image/duyxmy3.webp?t=${Date.now()}`,
    duyxmy4: `${IMAGE_BASE_URL}/image/duyxmy4.webp?t=${Date.now()}`,
    duyxmy5: `${IMAGE_BASE_URL}/image/duyxmy5.webp?t=${Date.now()}`,
    duyxmy6: `${IMAGE_BASE_URL}/image/duyxmy6.webp?t=${Date.now()}`,
    duyxmy7: `${IMAGE_BASE_URL}/image/duyxmy7.webp?t=${Date.now()}`,
    duyxmy8: `${IMAGE_BASE_URL}/image/duyxmy8.webp?t=${Date.now()}`,
    duyxmy9: `${IMAGE_BASE_URL}/image/duyxmy9.webp?t=${Date.now()}`,
    duyxmy10: `${IMAGE_BASE_URL}/image/duyxmy10.webp?t=${Date.now()}`,
    duyxmy11: `${IMAGE_BASE_URL}/image/duyxmy11.webp?t=${Date.now()}`,
    duyxmy12: `${IMAGE_BASE_URL}/image/duyxmy12.webp?t=${Date.now()}`,
    duyxmy13: `${IMAGE_BASE_URL}/image/duyxmy13.webp?t=${Date.now()}`,
    duyxmy14: `${IMAGE_BASE_URL}/image/duyxmy14.webp?t=${Date.now()}`,
    duyxmy15: `${IMAGE_BASE_URL}/image/duyxmy15.webp?t=${Date.now()}`,
    duyxmy16: `${IMAGE_BASE_URL}/image/duyxmy16.webp?t=${Date.now()}`,
    duyxmy17: `${IMAGE_BASE_URL}/image/duyxmy17.webp?t=${Date.now()}`,
    duyxmy18: `${IMAGE_BASE_URL}/image/duyxmy18.webp?t=${Date.now()}`,
    duyxmy19: `${IMAGE_BASE_URL}/image/duyxmy19.webp?t=${Date.now()}`,
    duyxmy20: `${IMAGE_BASE_URL}/image/duyxmy20.webp?t=${Date.now()}`,

    // Phuong x Hien gallery
    phuongxhien1: `${IMAGE_BASE_URL}/image/phuongxhien1.webp?t=${Date.now()}`,
    phuongxhien2: `${IMAGE_BASE_URL}/image/phuongxhien2.webp?t=${Date.now()}`,
    phuongxhien3: `${IMAGE_BASE_URL}/image/phuongxhien3.webp?t=${Date.now()}`,
    phuongxhien4: `${IMAGE_BASE_URL}/image/phuongxhien4.webp?t=${Date.now()}`,
    phuongxhien5: `${IMAGE_BASE_URL}/image/phuongxhien5.webp?t=${Date.now()}`,
    phuongxhien6: `${IMAGE_BASE_URL}/image/phuongxhien6.webp?t=${Date.now()}`,
    phuongxhien7: `${IMAGE_BASE_URL}/image/phuongxhien7.webp?t=${Date.now()}`,
    phuongxhien8: `${IMAGE_BASE_URL}/image/phuongxhien8.webp?t=${Date.now()}`,
    phuongxhien9: `${IMAGE_BASE_URL}/image/phuongxhien9.webp?t=${Date.now()}`,
    phuongxhien10: `${IMAGE_BASE_URL}/image/phuongxhien10.webp?t=${Date.now()}`,
    phuongxhien11: `${IMAGE_BASE_URL}/image/phuongxhien11.webp?t=${Date.now()}`,
    phuongxhien12: `${IMAGE_BASE_URL}/image/phuongxhien12.webp?t=${Date.now()}`,
    phuongxhien13: `${IMAGE_BASE_URL}/image/phuongxhien13.webp?t=${Date.now()}`,
    phuongxhien14: `${IMAGE_BASE_URL}/image/phuongxhien14.webp?t=${Date.now()}`,
    phuongxhien17: `${IMAGE_BASE_URL}/image/phuongxhien17.webp?t=${Date.now()}`,
    phuongxhien18: `${IMAGE_BASE_URL}/image/phuongxhien18.webp?t=${Date.now()}`,
    phuongxhien19: `${IMAGE_BASE_URL}/image/phuongxhien19.webp?t=${Date.now()}`,
    phuongxhien20: `${IMAGE_BASE_URL}/image/phuongxhien20.webp?t=${Date.now()}`,
    phuongxhien21: `${IMAGE_BASE_URL}/image/phuongxhien21.webp?t=${Date.now()}`,

    // Phuong x Hien 2 gallery
    phuongxhien2_1: `${IMAGE_BASE_URL}/image/phuongxhien2.1.webp?t=${Date.now()}`,
    phuongxhien2_2: `${IMAGE_BASE_URL}/image/phuongxhien2.2.webp?t=${Date.now()}`,
    phuongxhien2_3: `${IMAGE_BASE_URL}/image/phuongxhien2.3.webp?t=${Date.now()}`,
    phuongxhien2_4: `${IMAGE_BASE_URL}/image/phuongxhien2.4.webp?t=${Date.now()}`,
    phuongxhien2_5: `${IMAGE_BASE_URL}/image/phuongxhien2.5.webp?t=${Date.now()}`,
    phuongxhien2_6: `${IMAGE_BASE_URL}/image/phuongxhien2.6.webp?t=${Date.now()}`,
    phuongxhien2_7: `${IMAGE_BASE_URL}/image/phuongxhien2.7.webp?t=${Date.now()}`,
    phuongxhien2_8: `${IMAGE_BASE_URL}/image/phuongxhien2.8.webp?t=${Date.now()}`,
    phuongxhien2_9: `${IMAGE_BASE_URL}/image/phuongxhien2.9.webp?t=${Date.now()}`,
    phuongxhien2_10: `${IMAGE_BASE_URL}/image/phuongxhien2.10.webp?t=${Date.now()}`,
    phuongxhien2_11: `${IMAGE_BASE_URL}/image/phuongxhien2.11.webp?t=${Date.now()}`,
    phuongxhien2_12: `${IMAGE_BASE_URL}/image/phuongxhien2.12.webp?t=${Date.now()}`,
    phuongxhien2_13: `${IMAGE_BASE_URL}/image/phuongxhien2.13.webp?t=${Date.now()}`,
    phuongxhien2_14: `${IMAGE_BASE_URL}/image/phuongxhien2.14.webp?t=${Date.now()}`,

    // Phuong x Hien 3_ gallery
    phuongxhien3_1: `${IMAGE_BASE_URL}/image/phuongxhien3_1.webp?t=${Date.now()}`,
    phuongxhien3_2: `${IMAGE_BASE_URL}/image/phuongxhien3_2.webp?t=${Date.now()}`,
    phuongxhien3_3: `${IMAGE_BASE_URL}/image/phuongxhien3_3.webp?t=${Date.now()}`,
    phuongxhien3_4: `${IMAGE_BASE_URL}/image/phuongxhien3_4.webp?t=${Date.now()}`,
    phuongxhien3_5: `${IMAGE_BASE_URL}/image/phuongxhien3_5.webp?t=${Date.now()}`,
    phuongxhien3_6: `${IMAGE_BASE_URL}/image/phuongxhien3_6.webp?t=${Date.now()}`,
    phuongxhien3_7: `${IMAGE_BASE_URL}/image/phuongxhien3_7.webp?t=${Date.now()}`,
    phuongxhien3_8: `${IMAGE_BASE_URL}/image/phuongxhien3_8.webp?t=${Date.now()}`,
    phuongxhien3_9: `${IMAGE_BASE_URL}/image/phuongxhien3_9.webp?t=${Date.now()}`,
    phuongxhien3_10: `${IMAGE_BASE_URL}/image/phuongxhien3_10.webp?t=${Date.now()}`,
    phuongxhien3_11: `${IMAGE_BASE_URL}/image/phuongxhien3_11.webp?t=${Date.now()}`,
    phuongxhien3_12: `${IMAGE_BASE_URL}/image/phuongxhien3_12.webp?t=${Date.now()}`,
    phuongxhien3_13: `${IMAGE_BASE_URL}/image/phuongxhien3_13.webp?t=${Date.now()}`,
    phuongxhien3_14: `${IMAGE_BASE_URL}/image/phuongxhien3_14.webp?t=${Date.now()}`,
    phuongxhien3_15: `${IMAGE_BASE_URL}/image/phuongxhien3_15.webp?t=${Date.now()}`,
    phuongxhien3_16: `${IMAGE_BASE_URL}/image/phuongxhien3_16.webp?t=${Date.now()}`,
    phuongxhien3_17: `${IMAGE_BASE_URL}/image/phuongxhien3_17.webp?t=${Date.now()}`,
    phuongxhien3_18: `${IMAGE_BASE_URL}/image/phuongxhien3_18.webp?t=${Date.now()}`,
    phuongxhien3_19: `${IMAGE_BASE_URL}/image/phuongxhien3_19.webp?t=${Date.now()}`,
    phuongxhien3_20: `${IMAGE_BASE_URL}/image/phuongxhien3_20.webp?t=${Date.now()}`,
    phuongxhien3_21: `${IMAGE_BASE_URL}/image/phuongxhien3_21.webp?t=${Date.now()}`,

    // Elopment gallery
    elopement1: `${IMAGE_BASE_URL}/image/elopement1.webp?t=${Date.now()}`,
    elopement2: `${IMAGE_BASE_URL}/image/elopement2.webp?t=${Date.now()}`,
    elopement3: `${IMAGE_BASE_URL}/image/elopement3.webp?t=${Date.now()}`,
    elopement4: `${IMAGE_BASE_URL}/image/elopement4.webp?t=${Date.now()}`,
    elopement5: `${IMAGE_BASE_URL}/image/elopement5.webp?t=${Date.now()}`,
    elopement6: `${IMAGE_BASE_URL}/image/elopement6.webp?t=${Date.now()}`,
    elopement7: `${IMAGE_BASE_URL}/image/elopement7.webp?t=${Date.now()}`,
    elopement8: `${IMAGE_BASE_URL}/image/elopement8.webp?t=${Date.now()}`,
    elopement9: `${IMAGE_BASE_URL}/image/elopement9.webp?t=${Date.now()}`,
    elopement10: `${IMAGE_BASE_URL}/image/elopement10.webp?t=${Date.now()}`,
    elopement11: `${IMAGE_BASE_URL}/image/elopement11.webp?t=${Date.now()}`,
    elopement12: `${IMAGE_BASE_URL}/image/elopement12.webp?t=${Date.now()}`,
    elopement13: `${IMAGE_BASE_URL}/image/elopement13.webp?t=${Date.now()}`,
    elopement14: `${IMAGE_BASE_URL}/image/elopement14.webp?t=${Date.now()}`,
    elopement15: `${IMAGE_BASE_URL}/image/elopement15.webp?t=${Date.now()}`,
    elopement16: `${IMAGE_BASE_URL}/image/elopement16.webp?t=${Date.now()}`,

    // Duy x Yen gallery
    duyxyen1: `${IMAGE_BASE_URL}/image/duyxyen1.webp?t=${Date.now()}`,
    duyxyen2: `${IMAGE_BASE_URL}/image/duyxyen2.webp?t=${Date.now()}`,
    duyxyen3: `${IMAGE_BASE_URL}/image/duyxyen3.webp?t=${Date.now()}`,
    duyxyen4: `${IMAGE_BASE_URL}/image/duyxyen4.webp?t=${Date.now()}`,
    duyxyen5: `${IMAGE_BASE_URL}/image/duyxyen5.webp?t=${Date.now()}`,
    duyxyen6: `${IMAGE_BASE_URL}/image/duyxyen6.webp?t=${Date.now()}`,
    duyxyen7: `${IMAGE_BASE_URL}/image/duyxyen7.webp?t=${Date.now()}`,
    duyxyen8: `${IMAGE_BASE_URL}/image/duyxyen8.webp?t=${Date.now()}`,
    duyxyen9: `${IMAGE_BASE_URL}/image/duyxyen9.webp?t=${Date.now()}`,
    duyxyen10: `${IMAGE_BASE_URL}/image/duyxyen10.webp?t=${Date.now()}`,
    duyxyen11: `${IMAGE_BASE_URL}/image/duyxyen11.webp?t=${Date.now()}`,
    duyxyen12: `${IMAGE_BASE_URL}/image/duyxyen12.webp?t=${Date.now()}`,

    // Thoa x Binh gallery
    thoaxbinh1: `${IMAGE_BASE_URL}/image/thoaxbinh1.webp?t=${Date.now()}`,
    thoaxbinh2: `${IMAGE_BASE_URL}/image/thoaxbinh2.webp?t=${Date.now()}`,
    thoaxbinh3: `${IMAGE_BASE_URL}/image/thoaxbinh3.webp?t=${Date.now()}`,
    thoaxbinh4: `${IMAGE_BASE_URL}/image/thoaxbinh4.webp?t=${Date.now()}`,
    thoaxbinh5: `${IMAGE_BASE_URL}/image/thoaxbinh5.webp?t=${Date.now()}`,
    thoaxbinh6: `${IMAGE_BASE_URL}/image/thoaxbinh6.webp?t=${Date.now()}`,
    thoaxbinh7: `${IMAGE_BASE_URL}/image/thoaxbinh7.webp?t=${Date.now()}`,
    thoaxbinh8: `${IMAGE_BASE_URL}/image/thoaxbinh8.webp?t=${Date.now()}`,
    thoaxbinh9: `${IMAGE_BASE_URL}/image/thoaxbinh9.webp?t=${Date.now()}`,
    thoaxbinh10: `${IMAGE_BASE_URL}/image/thoaxbinh10.webp?t=${Date.now()}`,
    thoaxbinh11: `${IMAGE_BASE_URL}/image/thoaxbinh11.webp?t=${Date.now()}`,
    thoaxbinh12: `${IMAGE_BASE_URL}/image/thoaxbinh12.webp?t=${Date.now()}`,
    thoaxbinh13: `${IMAGE_BASE_URL}/image/thoaxbinh13.webp?t=${Date.now()}`,
    thoaxbinh14: `${IMAGE_BASE_URL}/image/thoaxbinh14.webp?t=${Date.now()}`,
    thoaxbinh15: `${IMAGE_BASE_URL}/image/thoaxbinh15.webp?t=${Date.now()}`,
    thoaxbinh16: `${IMAGE_BASE_URL}/image/thoaxbinh16.webp?t=${Date.now()}`,

    // An x Nghi gallery
    anxnghi1: `${IMAGE_BASE_URL}/image/anxnghi1.webp?t=${Date.now()}`,
    anxnghi2: `${IMAGE_BASE_URL}/image/anxnghi2.webp?t=${Date.now()}`,
    anxnghi3: `${IMAGE_BASE_URL}/image/anxnghi3.webp?t=${Date.now()}`,
    anxnghi4: `${IMAGE_BASE_URL}/image/anxnghi4.webp?t=${Date.now()}`,
    anxnghi5: `${IMAGE_BASE_URL}/image/anxnghi5.webp?t=${Date.now()}`,
    anxnghi6: `${IMAGE_BASE_URL}/image/anxnghi6.webp?t=${Date.now()}`,
    anxnghi7: `${IMAGE_BASE_URL}/image/anxnghi7.webp?t=${Date.now()}`,
    anxnghi8: `${IMAGE_BASE_URL}/image/anxnghi8.webp?t=${Date.now()}`,
    anxnghi9: `${IMAGE_BASE_URL}/image/anxnghi9.webp?t=${Date.now()}`,
    anxnghi10: `${IMAGE_BASE_URL}/image/anxnghi10.webp?t=${Date.now()}`,
    anxnghi11: `${IMAGE_BASE_URL}/image/anxnghi11.webp?t=${Date.now()}`,
    anxnghi12: `${IMAGE_BASE_URL}/image/anxnghi12.webp?t=${Date.now()}`,
    anxnghi13: `${IMAGE_BASE_URL}/image/anxnghi13.webp?t=${Date.now()}`,
    anxnghi14: `${IMAGE_BASE_URL}/image/anxnghi14.webp?t=${Date.now()}`,
    anxnghi15: `${IMAGE_BASE_URL}/image/anxnghi15.webp?t=${Date.now()}`,
    anxnghi16: `${IMAGE_BASE_URL}/image/anxnghi16.webp?t=${Date.now()}`,

    // An x Toan gallery
    anxtoan1: `${IMAGE_BASE_URL}/image/anxtoan1.webp?t=${Date.now()}`,
    anxtoan2: `${IMAGE_BASE_URL}/image/anxtoan2.webp?t=${Date.now()}`,
    anxtoan3: `${IMAGE_BASE_URL}/image/anxtoan3.webp?t=${Date.now()}`,
    anxtoan4: `${IMAGE_BASE_URL}/image/anxtoan4.webp?t=${Date.now()}`,
    anxtoan5: `${IMAGE_BASE_URL}/image/anxtoan5.webp?t=${Date.now()}`,
    anxtoan6: `${IMAGE_BASE_URL}/image/anxtoan6.webp?t=${Date.now()}`,
    anxtoan7: `${IMAGE_BASE_URL}/image/anxtoan7.webp?t=${Date.now()}`,
    anxtoan8: `${IMAGE_BASE_URL}/image/anxtoan8.webp?t=${Date.now()}`,
    anxtoan9: `${IMAGE_BASE_URL}/image/anxtoan9.webp?t=${Date.now()}`,
    anxtoan10: `${IMAGE_BASE_URL}/image/anxtoan10.webp?t=${Date.now()}`,
    anxtoan11: `${IMAGE_BASE_URL}/image/anxtoan11.webp?t=${Date.now()}`,
    anxtoan12: `${IMAGE_BASE_URL}/image/anxtoan12.webp?t=${Date.now()}`,
    anxtoan13: `${IMAGE_BASE_URL}/image/anxtoan13.webp?t=${Date.now()}`,
    anxtoan14: `${IMAGE_BASE_URL}/image/anxtoan14.webp?t=${Date.now()}`,
    anxtoan15: `${IMAGE_BASE_URL}/image/anxtoan15.webp?t=${Date.now()}`,

    // Han x Tung gallery
    hanxtung1: `${IMAGE_BASE_URL}/image/hanxtung1.webp?t=${Date.now()}`,
    hanxtung2: `${IMAGE_BASE_URL}/image/hanxtung2.webp?t=${Date.now()}`,
    hanxtung3: `${IMAGE_BASE_URL}/image/hanxtung3.webp?t=${Date.now()}`,
    hanxtung4: `${IMAGE_BASE_URL}/image/hanxtung4.webp?t=${Date.now()}`,
    hanxtung5: `${IMAGE_BASE_URL}/image/hanxtung5.webp?t=${Date.now()}`,
    hanxtung6: `${IMAGE_BASE_URL}/image/hanxtung6.webp?t=${Date.now()}`,
    hanxtung7: `${IMAGE_BASE_URL}/image/hanxtung7.webp?t=${Date.now()}`,
    hanxtung8: `${IMAGE_BASE_URL}/image/hanxtung8.webp?t=${Date.now()}`,
    hanxtung9: `${IMAGE_BASE_URL}/image/hanxtung9.webp?t=${Date.now()}`,
    hanxtung10: `${IMAGE_BASE_URL}/image/hanxtung10.webp?t=${Date.now()}`,
    hanxtung11: `${IMAGE_BASE_URL}/image/hanxtung11.webp?t=${Date.now()}`,
    hanxtung12: `${IMAGE_BASE_URL}/image/hanxtung12.webp?t=${Date.now()}`,
    hanxtung13: `${IMAGE_BASE_URL}/image/hanxtung13.webp?t=${Date.now()}`,
    hanxtung14: `${IMAGE_BASE_URL}/image/hanxtung14.webp?t=${Date.now()}`,
    hanxtung15: `${IMAGE_BASE_URL}/image/hanxtung15.webp?t=${Date.now()}`,
    hanxtung16: `${IMAGE_BASE_URL}/image/hanxtung16.webp?t=${Date.now()}`,
    hanxtung17: `${IMAGE_BASE_URL}/image/hanxtung17.webp?t=${Date.now()}`,
    hanxtung18: `${IMAGE_BASE_URL}/image/hanxtung18.webp?t=${Date.now()}`,
    hanxtung19: `${IMAGE_BASE_URL}/image/hanxtung19.webp?t=${Date.now()}`,
    hanxtung20: `${IMAGE_BASE_URL}/image/hanxtung20.webp?t=${Date.now()}`,

    // Josh x Linda gallery
    joshxlinda1: `${IMAGE_BASE_URL}/image/joshxlinda1.webp?t=${Date.now()}`,
    joshxlinda2: `${IMAGE_BASE_URL}/image/joshxlinda2.webp?t=${Date.now()}`,
    joshxlinda3: `${IMAGE_BASE_URL}/image/joshxlinda3.webp?t=${Date.now()}`,
    joshxlinda4: `${IMAGE_BASE_URL}/image/joshxlinda4.webp?t=${Date.now()}`,
    joshxlinda5: `${IMAGE_BASE_URL}/image/joshxlinda5.webp?t=${Date.now()}`,
    joshxlinda6: `${IMAGE_BASE_URL}/image/joshxlinda6.webp?t=${Date.now()}`,
    joshxlinda7: `${IMAGE_BASE_URL}/image/joshxlinda7.webp?t=${Date.now()}`,
    joshxlinda8: `${IMAGE_BASE_URL}/image/joshxlinda8.webp?t=${Date.now()}`,
    joshxlinda9: `${IMAGE_BASE_URL}/image/joshxlinda9.webp?t=${Date.now()}`,
    joshxlinda10: `${IMAGE_BASE_URL}/image/joshxlinda10.webp?t=${Date.now()}`,

    // Mai My x Toan Em gallery
    maimyxtoanem1: `${IMAGE_BASE_URL}/image/maimyxtoanem1.webp?t=${Date.now()}`,
    maimyxtoanem2: `${IMAGE_BASE_URL}/image/maimyxtoanem2.webp?t=${Date.now()}`,
    maimyxtoanem3: `${IMAGE_BASE_URL}/image/maimyxtoanem3.webp?t=${Date.now()}`,
    maimyxtoanem4: `${IMAGE_BASE_URL}/image/maimyxtoanem4.webp?t=${Date.now()}`,
    maimyxtoanem5: `${IMAGE_BASE_URL}/image/maimyxtoanem5.webp?t=${Date.now()}`,
    maimyxtoanem6: `${IMAGE_BASE_URL}/image/maimyxtoanem6.webp?t=${Date.now()}`,
    maimyxtoanem7: `${IMAGE_BASE_URL}/image/maimyxtoanem7.webp?t=${Date.now()}`,
    maimyxtoanem8: `${IMAGE_BASE_URL}/image/maimyxtoanem8.webp?t=${Date.now()}`,
    maimyxtoanem9: `${IMAGE_BASE_URL}/image/maimyxtoanem9.webp?t=${Date.now()}`,
    maimyxtoanem10: `${IMAGE_BASE_URL}/image/maimyxtoanem10.webp?t=${Date.now()}`,
    maimyxtoanem11: `${IMAGE_BASE_URL}/image/maimyxtoanem11.webp?t=${Date.now()}`,
    maimyxtoanem12: `${IMAGE_BASE_URL}/image/maimyxtoanem12.webp?t=${Date.now()}`,
    maimyxtoanem13: `${IMAGE_BASE_URL}/image/maimyxtoanem13.webp?t=${Date.now()}`,

    // Ngan x Nhat gallery
    nganxnhat1: `${IMAGE_BASE_URL}/image/nganxnhat1.webp?t=${Date.now()}`,
    nganxnhat2: `${IMAGE_BASE_URL}/image/nganxnhat2.webp?t=${Date.now()}`,
    nganxnhat3: `${IMAGE_BASE_URL}/image/nganxnhat3.webp?t=${Date.now()}`,
    nganxnhat4: `${IMAGE_BASE_URL}/image/nganxnhat4.webp?t=${Date.now()}`,
    nganxnhat5: `${IMAGE_BASE_URL}/image/nganxnhat5.webp?t=${Date.now()}`,
    nganxnhat6: `${IMAGE_BASE_URL}/image/nganxnhat6.webp?t=${Date.now()}`,
    nganxnhat7: `${IMAGE_BASE_URL}/image/nganxnhat7.webp?t=${Date.now()}`,
    nganxnhat8: `${IMAGE_BASE_URL}/image/nganxnhat8.webp?t=${Date.now()}`,
    nganxnhat9: `${IMAGE_BASE_URL}/image/nganxnhat9.webp?t=${Date.now()}`,
    nganxnhat10: `${IMAGE_BASE_URL}/image/nganxnhat10.webp?t=${Date.now()}`,
    nganxnhat11: `${IMAGE_BASE_URL}/image/nganxnhat11.webp?t=${Date.now()}`,
    nganxnhat12: `${IMAGE_BASE_URL}/image/nganxnhat12.webp?t=${Date.now()}`,
    nganxnhat13: `${IMAGE_BASE_URL}/image/nganxnhat13.webp?t=${Date.now()}`,
    nganxnhat14: `${IMAGE_BASE_URL}/image/nganxnhat14.webp?t=${Date.now()}`,
    nganxnhat15: `${IMAGE_BASE_URL}/image/nganxnhat15.webp?t=${Date.now()}`,
    nganxnhat16: `${IMAGE_BASE_URL}/image/nganxnhat16.webp?t=${Date.now()}`,
    nganxnhat17: `${IMAGE_BASE_URL}/image/nganxnhat17.webp?t=${Date.now()}`,

    // Nghia x Nguyet gallery
    nghiaxnguyet1: `${IMAGE_BASE_URL}/image/nghiaxnguyet1.webp?t=${Date.now()}`,
    nghiaxnguyet2: `${IMAGE_BASE_URL}/image/nghiaxnguyet2.webp?t=${Date.now()}`,
    nghiaxnguyet3: `${IMAGE_BASE_URL}/image/nghiaxnguyet3.webp?t=${Date.now()}`,
    nghiaxnguyet4: `${IMAGE_BASE_URL}/image/nghiaxnguyet4.webp?t=${Date.now()}`,
    nghiaxnguyet5: `${IMAGE_BASE_URL}/image/nghiaxnguyet5.webp?t=${Date.now()}`,
    nghiaxnguyet6: `${IMAGE_BASE_URL}/image/nghiaxnguyet6.webp?t=${Date.now()}`,
    nghiaxnguyet7: `${IMAGE_BASE_URL}/image/nghiaxnguyet7.webp?t=${Date.now()}`,
    nghiaxnguyet8: `${IMAGE_BASE_URL}/image/nghiaxnguyet8.webp?t=${Date.now()}`,
    nghiaxnguyet9: `${IMAGE_BASE_URL}/image/nghiaxnguyet9.webp?t=${Date.now()}`,
    nghiaxnguyet10: `${IMAGE_BASE_URL}/image/nghiaxnguyet10.webp?t=${Date.now()}`,
    nghiaxnguyet11: `${IMAGE_BASE_URL}/image/nghiaxnguyet11.webp?t=${Date.now()}`,
    nghiaxnguyet12: `${IMAGE_BASE_URL}/image/nghiaxnguyet12.webp?t=${Date.now()}`,
    nghiaxnguyet13: `${IMAGE_BASE_URL}/image/nghiaxnguyet13.webp?t=${Date.now()}`,
    nghiaxnguyet14: `${IMAGE_BASE_URL}/image/nghiaxnguyet14.webp?t=${Date.now()}`,
    nghiaxnguyet15: `${IMAGE_BASE_URL}/image/nghiaxnguyet15.webp?t=${Date.now()}`,

    // Thong x Huyen gallery
    thongxhuyen1: `${IMAGE_BASE_URL}/image/thongxhuyen1.webp?t=${Date.now()}`,
    thongxhuyen2: `${IMAGE_BASE_URL}/image/thongxhuyen2.webp?t=${Date.now()}`,
    thongxhuyen3: `${IMAGE_BASE_URL}/image/thongxhuyen3.webp?t=${Date.now()}`,
    thongxhuyen4: `${IMAGE_BASE_URL}/image/thongxhuyen4.webp?t=${Date.now()}`,
    thongxhuyen5: `${IMAGE_BASE_URL}/image/thongxhuyen5.webp?t=${Date.now()}`,
    thongxhuyen6: `${IMAGE_BASE_URL}/image/thongxhuyen6.webp?t=${Date.now()}`,
    thongxhuyen7: `${IMAGE_BASE_URL}/image/thongxhuyen7.webp?t=${Date.now()}`,
    thongxhuyen8: `${IMAGE_BASE_URL}/image/thongxhuyen8.webp?t=${Date.now()}`,
    thongxhuyen9: `${IMAGE_BASE_URL}/image/thongxhuyen9.webp?t=${Date.now()}`,
    thongxhuyen10: `${IMAGE_BASE_URL}/image/thongxhuyen10.webp?t=${Date.now()}`,
    thongxhuyen11: `${IMAGE_BASE_URL}/image/thongxhuyen11.webp?t=${Date.now()}`,
    thongxhuyen12: `${IMAGE_BASE_URL}/image/thongxhuyen12.webp?t=${Date.now()}`,

    // Tram x Max gallery
    tramxmax1: `${IMAGE_BASE_URL}/image/tramxmax1.webp?t=${Date.now()}`,
    tramxmax2: `${IMAGE_BASE_URL}/image/tramxmax2.webp?t=${Date.now()}`,
    tramxmax3: `${IMAGE_BASE_URL}/image/tramxmax3.webp?t=${Date.now()}`,
    tramxmax4: `${IMAGE_BASE_URL}/image/tramxmax4.webp?t=${Date.now()}`,
    tramxmax5: `${IMAGE_BASE_URL}/image/tramxmax5.webp?t=${Date.now()}`,
    tramxmax6: `${IMAGE_BASE_URL}/image/tramxmax6.webp?t=${Date.now()}`,
    tramxmax7: `${IMAGE_BASE_URL}/image/tramxmax7.webp?t=${Date.now()}`,
    tramxmax8: `${IMAGE_BASE_URL}/image/tramxmax8.webp?t=${Date.now()}`,
    tramxmax9: `${IMAGE_BASE_URL}/image/tramxmax9.webp?t=${Date.now()}`,
    tramxmax10: `${IMAGE_BASE_URL}/image/tramxmax10.webp?t=${Date.now()}`,
    tramxmax11: `${IMAGE_BASE_URL}/image/tramxmax11.webp?t=${Date.now()}`,
    tramxmax12: `${IMAGE_BASE_URL}/image/tramxmax12.webp?t=${Date.now()}`,
    tramxmax13: `${IMAGE_BASE_URL}/image/tramxmax13.webp?t=${Date.now()}`,
    tramxmax14: `${IMAGE_BASE_URL}/image/tramxmax14.webp?t=${Date.now()}`,
    tramxmax15: `${IMAGE_BASE_URL}/image/tramxmax15.webp?t=${Date.now()}`,
    tramxmax16: `${IMAGE_BASE_URL}/image/tramxmax16.webp?t=${Date.now()}`,
    tramxmax17: `${IMAGE_BASE_URL}/image/tramxmax17.webp?t=${Date.now()}`,
    tramxmax18: `${IMAGE_BASE_URL}/image/tramxmax18.webp?t=${Date.now()}`,
    tramxmax19: `${IMAGE_BASE_URL}/image/tramxmax19.webp?t=${Date.now()}`,

    // Viet  x Quynh gallery
    vietxquynh1: `${IMAGE_BASE_URL}/image/vietxquynh1.webp?t=${Date.now()}`,
    vietxquynh2: `${IMAGE_BASE_URL}/image/vietxquynh2.webp?t=${Date.now()}`,
    vietxquynh3: `${IMAGE_BASE_URL}/image/vietxquynh3.webp?t=${Date.now()}`,
    vietxquynh4: `${IMAGE_BASE_URL}/image/vietxquynh4.webp?t=${Date.now()}`,
    vietxquynh5: `${IMAGE_BASE_URL}/image/vietxquynh5.webp?t=${Date.now()}`,
    vietxquynh6: `${IMAGE_BASE_URL}/image/vietxquynh6.webp?t=${Date.now()}`,
    vietxquynh7: `${IMAGE_BASE_URL}/image/vietxquynh7.webp?t=${Date.now()}`,
    vietxquynh8: `${IMAGE_BASE_URL}/image/vietxquynh8.webp?t=${Date.now()}`,

    // Viet  x Quynh gallery
    vietxquynh1: `${IMAGE_BASE_URL}/image/vietxquynh1.webp?t=${Date.now()}`,
    vietxquynh2: `${IMAGE_BASE_URL}/image/vietxquynh2.webp?t=${Date.now()}`,
    vietxquynh3: `${IMAGE_BASE_URL}/image/vietxquynh3.webp?t=${Date.now()}`,
    vietxquynh4: `${IMAGE_BASE_URL}/image/vietxquynh4.webp?t=${Date.now()}`,
    vietxquynh5: `${IMAGE_BASE_URL}/image/vietxquynh5.webp?t=${Date.now()}`,
    vietxquynh6: `${IMAGE_BASE_URL}/image/vietxquynh6.webp?t=${Date.now()}`,
    vietxquynh7: `${IMAGE_BASE_URL}/image/vietxquynh7.webp?t=${Date.now()}`,
    vietxquynh8: `${IMAGE_BASE_URL}/image/vietxquynh8.webp?t=${Date.now()}`,

    // Viet x Quynh 2_ gallery
    vietxquynh2_1: `${IMAGE_BASE_URL}/image/vietxquynh2_1.webp?t=${Date.now()}`,
    vietxquynh2_2: `${IMAGE_BASE_URL}/image/vietxquynh2_2.webp?t=${Date.now()}`,
    vietxquynh2_3: `${IMAGE_BASE_URL}/image/vietxquynh2_3.webp?t=${Date.now()}`,
    vietxquynh2_4: `${IMAGE_BASE_URL}/image/vietxquynh2_4.webp?t=${Date.now()}`,
    vietxquynh2_5: `${IMAGE_BASE_URL}/image/vietxquynh2_5.webp?t=${Date.now()}`,
    vietxquynh2_6: `${IMAGE_BASE_URL}/image/vietxquynh2_6.webp?t=${Date.now()}`,
    vietxquynh2_7: `${IMAGE_BASE_URL}/image/vietxquynh2_7.webp?t=${Date.now()}`,
    vietxquynh2_8: `${IMAGE_BASE_URL}/image/vietxquynh2_8.webp?t=${Date.now()}`,
    vietxquynh2_9: `${IMAGE_BASE_URL}/image/vietxquynh2_9.webp?t=${Date.now()}`,
    vietxquynh2_10: `${IMAGE_BASE_URL}/image/vietxquynh2_10.webp?t=${Date.now()}`,

    // Tran x Tai 2_ Team gallery
    tranxtai2_1: `${IMAGE_BASE_URL}/image/tranxtai2_1.webp?t=${Date.now()}`,
    tranxtai2_2: `${IMAGE_BASE_URL}/image/tranxtai2_2.webp?t=${Date.now()}`,
    tranxtai2_3: `${IMAGE_BASE_URL}/image/tranxtai2_3.webp?t=${Date.now()}`,
    tranxtai2_4: `${IMAGE_BASE_URL}/image/tranxtai2_4.webp?t=${Date.now()}`,
    tranxtai2_5: `${IMAGE_BASE_URL}/image/tranxtai2_5.webp?t=${Date.now()}`,
    tranxtai2_6: `${IMAGE_BASE_URL}/image/tranxtai2_6.webp?t=${Date.now()}`,
    tranxtai2_7: `${IMAGE_BASE_URL}/image/tranxtai2_7.webp?t=${Date.now()}`,
    tranxtai2_8: `${IMAGE_BASE_URL}/image/tranxtai2_8.webp?t=${Date.now()}`,

    // Vy x Khang gallery
    vyxkhang1: `${IMAGE_BASE_URL}/image/vyxkhang1.webp?t=${Date.now()}`,
    vyxkhang2: `${IMAGE_BASE_URL}/image/vyxkhang2.webp?t=${Date.now()}`,
    vyxkhang3: `${IMAGE_BASE_URL}/image/vyxkhang3.webp?t=${Date.now()}`,
    vyxkhang4: `${IMAGE_BASE_URL}/image/vyxkhang4.webp?t=${Date.now()}`,
    vyxkhang5: `${IMAGE_BASE_URL}/image/vyxkhang5.webp?t=${Date.now()}`,
    vyxkhang6: `${IMAGE_BASE_URL}/image/vyxkhang6.webp?t=${Date.now()}`,
    vyxkhang7: `${IMAGE_BASE_URL}/image/vyxkhang7.webp?t=${Date.now()}`,
    vyxkhang8: `${IMAGE_BASE_URL}/image/vyxkhang8.webp?t=${Date.now()}`,
    vyxkhang9: `${IMAGE_BASE_URL}/image/vyxkhang9.webp?t=${Date.now()}`,

    // Duy x My 2_ gallery
    duyxmy2_1: `${IMAGE_BASE_URL}/image/duyxmy2_1.webp?t=${Date.now()}`,
    duyxmy2_2: `${IMAGE_BASE_URL}/image/duyxmy2_2.webp?t=${Date.now()}`,
    duyxmy2_3: `${IMAGE_BASE_URL}/image/duyxmy2_3.webp?t=${Date.now()}`,
    duyxmy2_4: `${IMAGE_BASE_URL}/image/duyxmy2_4.webp?t=${Date.now()}`,
    duyxmy2_5: `${IMAGE_BASE_URL}/image/duyxmy2_5.webp?t=${Date.now()}`,
    duyxmy2_6: `${IMAGE_BASE_URL}/image/duyxmy2_6.webp?t=${Date.now()}`,
    duyxmy2_7: `${IMAGE_BASE_URL}/image/duyxmy2_7.webp?t=${Date.now()}`,
    duyxmy2_8: `${IMAGE_BASE_URL}/image/duyxmy2_8.webp?t=${Date.now()}`,
    duyxmy2_9: `${IMAGE_BASE_URL}/image/duyxmy2_9.webp?t=${Date.now()}`,

    // Be Nang gallery
    benang1: `${IMAGE_BASE_URL}/image/benang1.webp?t=${Date.now()}`,
    benang2: `${IMAGE_BASE_URL}/image/benang2.webp?t=${Date.now()}`,
    benang3: `${IMAGE_BASE_URL}/image/benang3.webp?t=${Date.now()}`,
    benang4: `${IMAGE_BASE_URL}/image/benang4.webp?t=${Date.now()}`,
    benang5: `${IMAGE_BASE_URL}/image/benang5.webp?t=${Date.now()}`,
    benang6: `${IMAGE_BASE_URL}/image/benang6.webp?t=${Date.now()}`,
    benang7: `${IMAGE_BASE_URL}/image/benang7.webp?t=${Date.now()}`,
    benang8: `${IMAGE_BASE_URL}/image/benang8.webp?t=${Date.now()}`,
    benang9: `${IMAGE_BASE_URL}/image/benang9.webp?t=${Date.now()}`,

    // Trang x Vini gallery
    trangxvini1: `${IMAGE_BASE_URL}/image/trangxvini1.webp?t=${Date.now()}`,
    trangxvini2: `${IMAGE_BASE_URL}/image/trangxvini2.webp?t=${Date.now()}`,
    trangxvini3: `${IMAGE_BASE_URL}/image/trangxvini3.webp?t=${Date.now()}`,
    trangxvini4: `${IMAGE_BASE_URL}/image/trangxvini4.webp?t=${Date.now()}`,
    trangxvini5: `${IMAGE_BASE_URL}/image/trangxvini5.webp?t=${Date.now()}`,
    trangxvini6: `${IMAGE_BASE_URL}/image/trangxvini6.webp?t=${Date.now()}`,
    trangxvini7: `${IMAGE_BASE_URL}/image/trangxvini7.webp?t=${Date.now()}`,
    trangxvini8: `${IMAGE_BASE_URL}/image/trangxvini8.webp?t=${Date.now()}`,
    trangxvini9: `${IMAGE_BASE_URL}/image/trangxvini9.webp?t=${Date.now()}`,
    trangxvini10: `${IMAGE_BASE_URL}/image/trangxvini10.webp?t=${Date.now()}`,
    trangxvini11: `${IMAGE_BASE_URL}/image/trangxvini11.webp?t=${Date.now()}`,
    trangxvini12: `${IMAGE_BASE_URL}/image/trangxvini12.webp?t=${Date.now()}`,
    trangxvini13: `${IMAGE_BASE_URL}/image/trangxvini13.webp?t=${Date.now()}`,
    trangxvini14: `${IMAGE_BASE_URL}/image/trangxvini14.webp?t=${Date.now()}`,
    trangxvini15: `${IMAGE_BASE_URL}/image/trangxvini15.webp?t=${Date.now()}`,
    trangxvini16: `${IMAGE_BASE_URL}/image/trangxvini16.webp?t=${Date.now()}`,
    trangxvini17: `${IMAGE_BASE_URL}/image/trangxvini17.webp?t=${Date.now()}`,
    trangxvini18: `${IMAGE_BASE_URL}/image/trangxvini18.webp?t=${Date.now()}`,
    trangxvini19: `${IMAGE_BASE_URL}/image/trangxvini19.webp?t=${Date.now()}`,
    trangxvini20: `${IMAGE_BASE_URL}/image/trangxvini20.webp?t=${Date.now()}`,
    trangxvini21: `${IMAGE_BASE_URL}/image/trangxvini21.webp?t=${Date.now()}`,

    // Ant Team gallery
    antweddingteam2: `${IMAGE_BASE_URL}/image/antweddingteam2.webp?t=${Date.now()}`,
    antweddingteam5: `${IMAGE_BASE_URL}/image/antweddingteam5.webp?t=${Date.now()}`,
    antweddingteam6: `${IMAGE_BASE_URL}/image/antweddingteam6.webp?t=${Date.now()}`,
    antweddingteam8: `${IMAGE_BASE_URL}/image/antweddingteam8.webp?t=${Date.now()}`,
    antweddingteam9: `${IMAGE_BASE_URL}/image/antweddingteam9.webp?t=${Date.now()}`,
    antweddingteam10: `${IMAGE_BASE_URL}/image/antweddingteam10.webp?t=${Date.now()}`,
    antweddingteam11: `${IMAGE_BASE_URL}/image/antweddingteam11.webp?t=${Date.now()}`,
    antweddingteam12: `${IMAGE_BASE_URL}/image/antweddingteam12.webp?t=${Date.now()}`,
    antweddingteam13: `${IMAGE_BASE_URL}/image/antweddingteam13.webp?t=${Date.now()}`,
    antweddingteam14: `${IMAGE_BASE_URL}/image/antweddingteam14.webp?t=${Date.now()}`,
    antweddingteam15: `${IMAGE_BASE_URL}/image/antweddingteam15.webp?t=${Date.now()}`,
    antweddingteam16: `${IMAGE_BASE_URL}/image/antweddingteam16.webp?t=${Date.now()}`,
    antweddingteam17: `${IMAGE_BASE_URL}/image/antweddingteam17.webp?t=${Date.now()}`,
    antweddingteam18: `${IMAGE_BASE_URL}/image/antweddingteam18.webp?t=${Date.now()}`,
    antweddingteam19: `${IMAGE_BASE_URL}/image/antweddingteam19.webp?t=${Date.now()}`,
    antweddingteam20: `${IMAGE_BASE_URL}/image/antweddingteam20.webp?t=${Date.now()}`,
    antweddingteam21: `${IMAGE_BASE_URL}/image/antweddingteam21.webp?t=${Date.now()}`,
    antweddingteam22: `${IMAGE_BASE_URL}/image/antweddingteam22.webp?t=${Date.now()}`,
    antweddingteam23: `${IMAGE_BASE_URL}/image/antweddingteam23.webp?t=${Date.now()}`,
    antweddingteam24: `${IMAGE_BASE_URL}/image/antweddingteam24.webp?t=${Date.now()}`,
    antweddingteam25: `${IMAGE_BASE_URL}/image/antweddingteam25.webp?t=${Date.now()}`,
}
